CS/Models/CatalogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCxDocumentViewerWithReportServerMVC3.Models {
    public class CatalogModel {
        public IEnumerable<ReportModel> ReportList { get; set; }
    }
}

CS/Models/ReportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCxDocumentViewerWithReportServerMVC3.Models {
    public class ReportModel {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
    }
}

CS/Controllers/DocumentViewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using DevExpress.XtraReports.Web.DocumentViewer;
using MVCxDocumentViewerWithReportServerMVC3.Models;

namespace MVCxDocumentViewerWithReportServerMVC3.Controllers {
    public class DocumentViewerController : Controller {
        public ActionResult DocumentViewer(ReportModel model) {
            return View(model);
        }

        public ActionResult DocumentViewerPartial(int reportID) {
            return PartialView("DocumentViewerPartial", new ReportModel() { ReportID = reportID });
        }

        public ActionResult DocumentViewerExportTo(int reportID) {
            MVCxDocumentViewerRemoteSourceSettings remoteSourceSettings = new MVCxDocumentViewerRemoteSourceSettings() {
                AuthenticationType = DevExpress.ReportServer.Printing.AuthenticationType.Windows,
                ReportId = reportID,
                ServerUri = "http://localhost:83/"
            };
            return DocumentViewerExtension.ExportToAsync(remoteSourceSettings, Request).Result;
        }
    }
}

CS/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Web.Mvc;
using DevExpress.ReportServer.ServiceModel.Client;
using DevExpress.ReportServer.ServiceModel.DataContracts;
using DevExpress.Web.Mvc;
using MVCxDocumentViewerWithReportServerMVC3.Models;

namespace MVCxDocumentViewerWithReportServerMVC3.Controllers {
    public class GalleryController : Controller {
        public ActionResult ReportList() {
            EndpointAddress authEndpoint = new EndpointAddress("http://localhost:83/WindowsAuthentication/AuthenticationService.svc");
            AuthenticationServiceClientFactory authClientFactory = new AuthenticationServiceClientFactory(authEndpoint, DevExpress.ReportServer.Printing.AuthenticationType.Windows);
            FormsAuthenticationEndpointBehavior behavior = new DevExpress.ReportServer.ServiceModel.Client.FormsAuthenticationEndpointBehavior();
            authClientFactory.ChannelFactory.Endpoint.Behaviors.Add(behavior);
            IAuthenticationServiceClient authClient = authClientFactory.Create();

            TaskCompletionSource<bool> authTcs = new TaskCompletionSource<bool>();
            authClient.UseSynchronizationContext = false;
            authClient.Login(null, null, null, (e) => {
                if(e.Error != null)
                    authTcs.SetException(e.Error);
                else
                    authTcs.SetResult(e.Result);
            });
            if(!authTcs.Task.Result)
                throw new Exception("Failed to login to the Report Server");

            EndpointAddress serviceFacadeEndpoint = new EndpointAddress("http://localhost:83/ReportServerFacade.svc");
            ReportServerClientFactory serverFacadeClientFactory = new ReportServerClientFactory(serviceFacadeEndpoint);
            serverFacadeClientFactory.ChannelFactory.Endpoint.Behaviors.Add(behavior);
            IReportServerClient reportServerClient = serverFacadeClientFactory.Create();
            TaskCompletionSource<IEnumerable<ReportModel>> tcs = new TaskCompletionSource<IEnumerable<ReportModel>>();
            reportServerClient.UseSynchronizationContext = false;
            reportServerClient.GetReports(null, (args) => {
                if(args.Error != null)
                    tcs.SetException(args.Error);
                else {
                    IEnumerable<ReportCatalogItemDto> reports = args.Result;
                    tcs.SetResult(reports == null ? null : reports.Select(x => new ReportModel() { ReportID = x.Id, ReportName = x.Name }));
                }
            });
            IEnumerable<ReportModel> taskResult = tcs.Task.Result;
            return View(taskResult);
        }

        public ActionResult DocumentViewer(ReportModel model) {
            return RedirectToAction("DocumentViewer", "DocumentViewer", model);
        }
    }
}

CS/Views/DocumentViewer/DocumentViewer.cshtml
@model ReportModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("DocumentViewerPartial", Model)

CS/Views/DocumentViewer/DocumentViewerPartial.cshtml
@model ReportModel
@Html.DevExpress().DocumentViewer(
    settings => {
        settings.Name = "DocumentViewer";
        settings.SettingsRemoteSource.AuthenticationType = DevExpress.ReportServer.Printing.AuthenticationType.Windows;
        settings.SettingsRemoteSource.ReportId = Model.ReportID;
        settings.SettingsRemoteSource.ServerUri = "http://localhost:83/";
        settings.CallbackRouteValues = new { Controller = "DocumentViewer", Action = "DocumentViewerPartial", ReportID = Model.ReportID };
        settings.ExportRouteValues = new { Controller = "DocumentViewer", Action = "DocumentViewerExportTo", ReportID = Model.ReportID };
    }).GetHtml()

CS/Views/Gallery/ReportList.cshtml
@model IEnumerable<ReportModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div>
        @foreach(ReportModel reportInfo in Model) { 
            @Html.ActionLink(reportInfo.ReportName, "DocumentViewer", reportInfo);
            <br />
        }
        <br />
    </div>

CS/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>Report Server Catalogue</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionType = ExtensionType.DocumentViewer },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
    )
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    @Html.DevExpress().GetScripts(
        new Script { ExtensionType = ExtensionType.DocumentViewer},
        new Script { ExtensionSuite = ExtensionSuite.Editors }
    )
        
</head>

<body>
    <div>
        <div id="header">
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Report List", "ReportList", "Gallery")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>